#!/usr/bin/env python3
"""Regenerate results/CLAIMS.md from the verified artefacts in results/.

For every (Delta, D) cell it takes the largest emitted graph that beats the
published record, re-runs the verifiers, and writes the certificate table.  A
candidate that fails any verifier is listed as FAILED, never quietly dropped.
"""
import glob
import json
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results")
TABLE = os.path.join(HERE, "table_current.json")


def run(script, path):
    p = subprocess.run([sys.executable, os.path.join(HERE, script), path],
                       capture_output=True, text=True)
    return p.returncode == 0, p.stdout.strip()


def main():
    tbl = json.load(open(TABLE))
    cells = tbl["cells"]
    best = {}
    for jf in glob.glob(os.path.join(RESULTS, "*.json")):
        try:
            m = json.load(open(jf))
        except Exception:
            continue
        if "delta" not in m or "S" not in m:
            continue
        ef = os.path.splitext(jf)[0] + ".edges"
        if not os.path.exists(ef):
            continue
        key = (m["delta"], m["D"])
        rec = cells.get("%d,%d" % key, {}).get("N")
        if rec is None or m["N"] <= rec:
            continue
        if key not in best or m["N"] > best[key][0]["N"]:
            best[key] = (m, ef)

    out = []
    out.append("# Degree/diameter — verified record candidates\n")
    out.append("Incumbents are from the live table\n"
               "<https://web.mat.upc.edu/francesc.comellas/delta-d/table_degree_diameter.html>\n"
               "(mirrored in `data/table_raw.html`; re-fetched and byte-identical, md5\n"
               "`f2b84a3ecf8cb949035815105accd040`, at the time of writing).\n")
    out.append("Generated by `make_claims.py` — every row below was re-derived from its\n"
               "group data by `emit_graph.py` (pure Python, independent of the search\n"
               "engines) and then re-verified by the checks named in its row.\n")
    out.append("## Verifiers\n")
    out.append("| script | what it does |\n|---|---|")
    out.append("| `verify_dd.py` | pure-stdlib reference: simplicity, degree, connectivity, "
               "BFS from **every** vertex. O(N·E), so it is used on the small graphs. |")
    out.append("| `verify_big.py` | the same exhaustive all-pairs check done bit-parallel "
               "(64 sources per pass, numpy) — every ordered pair, in seconds. |")
    out.append("| `verify_vt.py` | *proves* vertex-transitivity from the edge list — two "
               "suggested left-translation permutations are checked to be bijections that map "
               "every edge to an edge, and the group they generate is checked to be transitive "
               "— after which one BFS gives the diameter. A wrong suggestion fails the check "
               "rather than yielding a wrong answer. |\n")

    rows = []
    for key in sorted(best, key=lambda k: (k[1], k[0])):
        m, ef = best[key]
        rec = cells["%d,%d" % key]["N"]
        checks = []
        for script in ("verify_big.py", "verify_vt.py"):
            ok, txt = run(script, ef)
            checks.append((script, ok, txt))
        if m["N"] <= 5000:
            ok, txt = run("verify_dd.py", ef)
            checks.append(("verify_dd.py", ok, txt))
        allok = all(c[1] for c in checks)
        rows.append((key, m, ef, rec, checks, allok))

    out.append("## Summary\n")
    out.append("| cell | published record | found here | margin | group | verified |")
    out.append("|------|------------------|-----------|--------|-------|----------|")
    for (delta, D), m, ef, rec, checks, allok in rows:
        grp = "Z_%d ⋊_%d Z_%d" % (m["m"], m["a"], m["n"]) if m.get("model") != "affine2" \
            else "(Z_%d)² ⋊ Z_%d" % (m["p"], m["n"])
        out.append("| (%d,%d) | %d | **%d** | +%d | `%s` | %s |"
                   % (delta, D, rec, m["N"], m["N"] - rec, grp,
                      "yes" if allok else "**FAILED**"))
    out.append("")

    for (delta, D), m, ef, rec, checks, allok in rows:
        out.append("---\n")
        out.append("## (Δ, D) = (%d, %d):  N = %d   (published record %d, +%d)\n"
                   % (delta, D, m["N"], rec, m["N"] - rec))
        out.append("| | |\n|---|---|")
        out.append("| order | **%d** |" % m["N"])
        out.append("| degree | %d (regular) |" % delta)
        out.append("| diameter | %d (exact) |" % D)
        out.append("| edges | %d |" % m["edges"])
        out.append("| group | `%s` |" % m["group"])
        out.append("| connection set | `%s` |" % m["S"])
        out.append("| files | `%s.{edges,adjlist,json,txt}` |"
                   % os.path.basename(os.path.splitext(ef)[0]))
        out.append("")
        out.append("Element `(i,j)` is stored at index `j*%d + i` and\n"
                   "`(i1,j1)·(i2,j2) = (i1 + %d^{j1}·i2 mod %d, j1+j2 mod %d)`.\n"
                   % (m["m"], m["a"], m["m"], m["n"]))
        for script, ok, txt in checks:
            out.append("```\n$ python3 %s %s\n%s\n```\n"
                       % (script, os.path.relpath(ef, HERE), txt))

    open(os.path.join(RESULTS, "CLAIMS.md"), "w").write("\n".join(out) + "\n")
    print("wrote results/CLAIMS.md with %d cells" % len(rows))
    for (delta, D), m, ef, rec, checks, allok in rows:
        print("  (%d,%d)  %d > %d  (+%d)  %s"
              % (delta, D, m["N"], rec, m["N"] - rec, "verified" if allok else "FAILED"))
    return 0 if all(r[5] for r in rows) else 1


if __name__ == "__main__":
    sys.exit(main())
