#!/usr/bin/env python3
r"""Generate paper/covering/tables_generated.tex from the live result state.

Inputs:  cov/results/final_records.json   (UB records, written by cov/engine/tally.py)
         cov/lb/results/lb_master.json    (LB master table, written by cov/lb/report.py
                                           --certs cov/lb/certs_all --out ...lb_master.json)
         cov/bounds.json                  (Keri 2011 incumbents + source keys)
Output:  paper/covering/tables_generated.tex  (\ubtable and \lbtable macros)

Re-run after any tally refresh; the paper \input's the output, so the final
build always reflects the current verified state.
"""
import json, math, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

UB_KEY_TEXT = {
    # q>=6 table legend (keri_6-21_tables.pdf) + q=4-5 legend where noted
    "c": r"monotonicity $K_q(n{+}1,R{+}1)\le K_q(n,R)$",
    "e": r"$K_q(n{+}1,R)\le q\,K_q(n,R)$",
    "f": r"direct sum",
    "d": r"Bhandari--Durairajan~\cite{BhandariDurairajan1996}",  # q=4,5 table
    "j": r"alphabet product rule",              # q>=6 legend: $K_{tq}(n,R)\le tK_q(n,R)$ / $\sigma$-rule
    "n": r"K\'eri--\"Osterg\aa rd~\cite{KeriOstergard2005}",
    "q": r"Rivas Soriano (attributed in~\cite{Keri})",
    "z": r"K\'eri 2009 updates recorded in~\cite{Keri}",
    "k": r"bound for smaller $q$",
    "b": r"Taussky--Todd 1948",
}
# cells whose descent hit a wall (a full long-budget attempt at M-1 failed);
# everything else is a snapshot of an unconverged descent.
WALLED = {(6,8,4), (6,9,5), (6,9,4), (7,8,4), (6,7,3), (6,8,3), (5,11,5), (8,8,4),
          (7,9,4), (6,10,4),  # 2026-08-21: two consecutive 3000s x 12-core failures each
          (7,10,5), (8,10,5), (9,9,5), (10,9,5),  # GPU: 3 single-step fails at 800-1600s each
          (9,10,5),  # 2026-08-22: 3 single-step fails at 1600/3200/6400s (best uncov 2)
          (8,6,4), (12,6,4), (13,6,4), (14,6,4), (15,6,4),  # 2026-08-23: two consecutive 3600s x 40-worker fails at M-1
          (6,10,5), (8,8,5), (7,9,5),   # 2026-08-23/24: two consecutive 3600s x 20-worker fails at M-1
          (10,10,5)}  # 2026-08-24: 3 single-step fails at 1800/3600/5217s (best uncov 3/4/1)


def sphere_lb(q, n, R):
    V = sum(math.comb(n, i) * (q - 1) ** i for i in range(R + 1))
    return -(-q ** n // V)  # ceil


def main():
    recs = json.load(open("cov/results/final_records.json"))
    bounds = {(e["q"], e["n"], e["R"]): e for e in json.load(open("cov/bounds.json"))["entries"]}
    lb_master_path = "cov/lb/results/lb_master.json"
    if not os.path.exists(lb_master_path):
        sys.exit(f"missing {lb_master_path}: run cov/lb/report.py --certs cov/lb/certs_all --out {lb_master_path}")
    lb_rows = [r for r in json.load(open(lb_master_path)) if r.get("improves_best_known")]

    lb_improved = {(r["q"], r["n"], r["R"]): r["K_lower_bound"] for r in lb_rows}

    # producing method per cell: T = transform engine (Sec. 5), M = monotonicity
    # propagation of another new bound, L = engineered local search (Sec. 4).
    GPU_CELLS = {(7,10,5), (8,10,5), (9,9,5), (9,10,5), (10,9,5), (10,10,5),
                 (10,10,6)}
    ub_lines = []
    used_keys = []
    for r in sorted(recs, key=lambda r: (r["q"], r["n"], r["R"])):
        q, n, R, M = r["q"], r["n"], r["R"], r["ours"]
        e = bounds[(q, n, R)]
        pct = 100.0 * (e["ub"] - M) / e["ub"]
        key = e["ub_key"] or "--"
        if key not in used_keys:
            used_keys.append(key)
        conv = "" if (q, n, R) in WALLED else r"$^{\downarrow}$"
        newlb = lb_improved.get((q, n, R))
        lbtxt = rf"\textbf{{{newlb}}}" if newlb else str(e["lb"])
        if (q, n, R) in GPU_CELLS:
            meth = "T"
        elif "monotonicity" in (r.get("produced_by") or ""):
            meth = "M"
        else:
            meth = "L"
        ub_lines.append(
            rf"$\Kq{{{q}}}{{{n}}}{{{R}}}$ & {lbtxt}--{e['ub']} & {sphere_lb(q,n,R)} & "
            rf"\textbf{{{M}}}{conv} & $-{e['ub']-M}$ & ${pct:.1f}\%$ & "
            rf"\texttt{{{key}}} & {meth} \\")
    key_legend = "; ".join(
        rf"\texttt{{{k}}} = {UB_KEY_TEXT.get(k, '?')}" for k in sorted(used_keys))

    lb_lines = []
    for r in sorted(lb_rows, key=lambda r: (r["q"], r["n"], r["R"])):
        q, n, R = r["q"], r["n"], r["R"]
        lb_lines.append(
            rf"$\Kq{{{q}}}{{{n}}}{{{R}}}$ & {sphere_lb(q,n,R)} & {r['best_known_lb']} "
            rf"(\texttt{{{r['keri_lb_key']}}}) & \textbf{{{r['K_lower_bound']}}} \\")
    half = (len(lb_lines) + 1) // 2
    lb_head = (r"\begin{tabular}{lccc}" "\n" r"\toprule" "\n"
               r"cell & sphere & prev.\ LB & new LB \\" "\n" r"\midrule")
    lb_left = lb_head + "\n" + "\n".join(lb_lines[:half]) + "\n" + r"\bottomrule" + "\n" + r"\end{tabular}"
    lb_right = lb_head + "\n" + "\n".join(lb_lines[half:]) + "\n" + r"\bottomrule" + "\n" + r"\end{tabular}"

    out = r"""% AUTO-GENERATED by scripts/paper_tables.py -- do not edit by hand.
\newcommand{\ubkeylegend}{""" + key_legend + r"""}
\newcommand{\ubtable}{%
\begin{tabular}{lccccccc}
\toprule
cell & previous bounds & sphere & new UB & $\Delta$ & $\Delta\%$ & key & via \\
\midrule
""" + "\n".join(ub_lines) + r"""
\bottomrule
\end{tabular}}
\newcommand{\lbtable}{%
""" + lb_left + r"\hspace{1.5em}" + lb_right + r"""}
"""
    open("paper/covering/tables_generated.tex", "w").write(out)
    print(f"wrote paper/covering/tables_generated.tex: {len(ub_lines)} UB rows, {len(lb_lines)} LB rows")

    # appendix: the K6(8,4)<=166 code, 4 words per line (a walled, stable cell)
    words = [l.strip() for l in open("cov/results/K6_8_4_M166.txt") if l.strip()]
    assert len(words) == 166
    with open("paper/covering/appendix_code.tex", "w") as f:
        f.write("% AUTO-GENERATED by scripts/paper_tables.py\n\\begin{verbatim}\n")
        for i in range(0, len(words), 4):
            f.write("  ".join(words[i:i+4]) + "\n")
        f.write("\\end{verbatim}\n")
    print("wrote paper/covering/appendix_code.tex")


if __name__ == "__main__":
    main()
